from crewai import Task

def create_tasks(agents, user_requirement):
    pm, tl, dev, validator, tester = agents

    # Task 1: PRD & Architecture
    task_define_project = Task(
        description=f"""Analyze the following User Requirement:
        <user_requirement>
        {user_requirement}
        </user_requirement>

        1. Create a Product Requirements Document (PRD) at 'PRD.md'.
        2. Create a System Architecture document at 'ARCHITECTURE.md'.
        Ensure the architecture is modular and suitable for an autonomous team.""",
        expected_output="A 'PRD.md' and 'ARCHITECTURE.md' file.",
        agent=pm
    )

    # Task 2: Task List creation
    task_create_tasks = Task(
        description="""Read 'PRD.md' and 'ARCHITECTURE.md'.
        Break down the project into a step-by-step JSON Task List.
        Save this list to 'TASK_LIST.json'. The list should be an array of objects with 'id', 'name', 'description', and 'files' keys.""",
        expected_output="A 'TASK_LIST.json' file containing the development roadmap.",
        agent=tl,
        context=[task_define_project]
    )

    # Task 3: Implementation (Recursive Loop Mock - for the demo we will just do a single pass of a core component)
    # In a full recursive system, we would dynamically generate these tasks based on the JSON output.
    # For this implementation, we will instruct the Dev to scaffold the project structure based on the architecture.
    task_scaffold_project = Task(
        description="""Read 'ARCHITECTURE.md' and 'TASK_LIST.json'.
        Create the directory structure and empty file placeholders for the project.
        Then, implement the main entry point file as defined in the architecture.""",
        expected_output="Project directories and the main entry point file created.",
        agent=dev,
        context=[task_create_tasks]
    )

    # Task 4: Validation
    task_validate_core = Task(
        description="""Read the code generated by the Developer (specifically the main entry point).
        Analyze it for Logical Integrity, Security, and Performance.
        Write a report to 'VALIDATION_REPORT.md'.""",
        expected_output="A 'VALIDATION_REPORT.md' file with feedback.",
        agent=validator,
        context=[task_scaffold_project]
    )

    return [task_define_project, task_create_tasks, task_scaffold_project, task_validate_core]
